const products = [
    {
      id: 1,
      name: "Luxury Recliner",
      description: "Perfect for relaxing in style and comfort",
      price: 499,
      images: [
        "https://m.media-amazon.com/images/I/6167riKZSNL._AC_UF894,1000_QL80_.jpg",
        "https://www.wardbrothers.co.uk/cdn/shop/articles/parker-knoll-boston-recliner-chair.jpg?v=1691501058",
        "https://www.nilkamalhomes.com/cdn/shop/files/Bakewell3strLS.jpg?crop=center&height=300&v=1707457971&width=300",
        "https://www.nilkamalhomes.com/cdn/shop/files/BEATRIX1SSOFALS2.jpg?crop=center&height=300&v=1727072077&width=300",
      ],
      availableColors: ["Brown", "Black", "Grey"],
      designs: ["Modern", "Classic", "Minimalist"],
      customizationOption:
        "Available with optional footrest and adjustable back support.",
      dimensions: "86(L) x 33(B) x 39(H)",
      upholsteryMaterial: "Leather",
      foamType: "High Resilient Foam",
      cushion: "Soft",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Comfortable and stylish with clean lines and reclining mechanism.",
        "Material: Soft, durable leather upholstery.",
        "Durability: Built with a sturdy wood frame and reinforced support.",
        "Comfort: Plush cushions filled with high-density foam.",
      ],
    },
    {
      id: 2,
      name: "Classic Sofa",
      description: "A spacious and cozy sofa set designed for relaxation",
      price: 799,
      images: [
        "https://blog.luxury-italianfurniture.com/hubfs/Italian-classic-sofa-set-1.jpg",
        "https://i.pinimg.com/564x/da/e8/c6/dae8c62207b8d208cecdf6418f77c7c4.jpg",
        "https://www.vimercatimeda.com/sites/default/files/styles/fullscreen/public/immagine/8_18.jpg?itok=XFKierV1",
        "https://media.furniturevillage.co.uk/i/fv/PRODZFRSP000000000054575_shackleton_4-seater-leather-sofa__lifestyle?$medium$&fmt=auto&fmt=auto&w=579"
      ],
      availableColors: ["Beige", "Light Grey", "Navy"],
      designs: ["Contemporary", "Relaxed"],
      customizationOption: "Customizable fabric colors and cushion firmness.",
      dimensions: "90(L) x 36(B) x 38(H)",
      upholsteryMaterial: "High-Quality Fabric",
      foamType: "High-Density Foam",
      cushion: "Medium Firm",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Comfortable and spacious with large armrests for ultimate relaxation.",
        "Material: Soft, durable fabric with a modern feel.",
        "Durability: Strong frame with durable stitching.",
        "Comfort: Cushions filled with high-density foam for lasting comfort.",
      ],
    },
    {
      id: 3,
      name: "Modern Dining Table",
      description: "A sleek and stylish dining table that fits perfectly in modern spaces",
      price: 349,
      images: [
        "https://www.amsiatelier.com/wp-content/uploads/2023/03/luna-dt.webp",
        "https://hogfurniture.co/cdn/shop/files/Marble-Finish_Rectangular_Dining_Table_Set_with_Padded_Chairs.jpg?v=1729755706",
        "https://cdn.pixelspray.io/v2/black-bread-289bfa/TIw66q/wrkr/t.resize(h:500,w:500)/data/Westelm/16022024/10056040_1.jpg",
        "https://www.vikinterio.com/product-images/VIK_R_4_1.jpg/473239000004870045/900x900"
      ],
      availableColors: ["Charcoal", "Dusty Pink"],
      designs: ["Minimalist", "Sleek"],
      customizationOption: "Available with custom upholstery options.",
      dimensions: "55(L) x 30(B) x 35(H)",
      upholsteryMaterial: "Velvet",
      foamType: "Memory Foam",
      cushion: "Soft",
      legsMaterial: "Metal",
      salientFeatures: [
        "Design: Modern design with clean lines and a sleek profile.",
        "Material: Luxurious velvet upholstery with a soft feel.",
        "Durability: Sturdy metal legs with high-quality velvet.",
        "Comfort: Memory foam cushions for enhanced comfort.",
      ],
    },
    {
      id: 4,
      name: "Queen Bed",
      description: "A comfortable and stylish queen-sized bed for a good night's sleep",
      price: 799,
      images: [
        "https://www.divanbedwarehouse.co.uk/cdn/shop/products/DBWday2255385_84_RT.jpg?v=1620655678&width=4842",
        "https://5.imimg.com/data5/ECOM/Default/2023/9/340541579/LH/AU/NN/186159128/wb1.jpg",
        "https://bevmarks.com.au/cdn/shop/files/Kapella-Bed_534f49db-386d-4ad0-acc0-01f9eb5dd740_1200x1200.jpg?v=1707364453",
        "https://w0.peakpx.com/wallpaper/953/808/HD-wallpaper-stylish-interior-design-bedroom-classic-style-white-gray-bedroom-large-wooden-bed.jpg",

      ],
      availableColors: ["Dark Grey", "Beige"],
      designs: ["Modern", "Spacious"],
      customizationOption: "Customizable with different mattress options.",
      dimensions: "80(L) x 60(B) x 40(H)",
      upholsteryMaterial: "Leatherette",
      foamType: "Memory Foam",
      cushion: "Firm",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: A modern, spacious bed for a relaxing sleep experience.",
        "Material: Soft leatherette that’s durable and easy to clean.",
        "Durability: Strong wood frame with reinforced support.",
        "Comfort: Memory foam cushion for enhanced sleep support.",
      ],
    },
    {
      id: 5,
      name: "Coffee Table",
      description: "A stylish and functional coffee table for your living room",
      price: 249,
      images: [
        "https://www.10stunninghomes.com/wp-content/uploads/modern-coffee-table-living-room.jpg",
        "https://target.scene7.com/is/image/Target/GUEST_113894c4-6321-4dba-bbc3-db66d2a3cf78?wid=488&hei=488&fmt=pjpeg",
        "https://ak1.ostkcdn.com/images/products/is/images/direct/d0fbcc89ae58769cc705c12e3e1dac7d98ca350b/Modern-Round-Coffee-Table-with-2-large-Drawers.jpg?impolicy=medium",
        "https://media.karousell.com/media/photos/products/2023/7/26/stylish_round_coffee_table_2in_1690359990_26171d8b_progressive"
      ],
      availableColors: ["Wooden", "Black", "White"],
      designs: ["Modern", "Functional"],
      customizationOption: "Customizable in various finishes and sizes.",
      dimensions: "48(L) x 24(B) x 18(H)",
      upholsteryMaterial: "Wood",
      foamType: "N/A",
      cushion: "N/A",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Elegant and functional with plenty of storage space.",
        "Material: High-quality wood for durability and style.",
        "Durability: Sturdy construction for long-lasting use.",
        "Comfort: Easy-to-clean surface for convenience.",
      ],
    },
    {
      id: 6,
      name: "Bedside Table",
      description: "A small and functional bedside table to complement your bedroom",
      price: 149,
      images: [
        "https://thumbs.dreamstime.com/b/contemporary-monochrome-bedroom-design-stylish-bedside-table-near-bed-neon-lights-behihd-headboard-lamp-black-lampshade-59224789.jpg",
        "https://m.media-amazon.com/images/I/61dVoCFbV5L._AC_UF894,1000_QL80_.jpg",
        "https://media.istockphoto.com/id/1264970108/photo/portrait-white-frame-mockup-on-retro-wooden-bedside-table-modern-white-ceramic-vase-dry.jpg?s=612x612&w=0&k=20&c=T3IBI3d58bs8gbmtB2b0J_0vopW2nuKeTG3XwgKtpOQ=",
        "https://www.younghouselove.com/wp-content/uploads/2022/10/Butcher-Block-Nightstand-With-Penny-On-Bed-1024x753.jpg"
      ],
      availableColors: ["Wooden", "Grey", "Black"],
      designs: ["Contemporary", "Compact"],
      customizationOption: "Available in various wood finishes and sizes.",
      dimensions: "20(L) x 15(B) x 24(H)",
      upholsteryMaterial: "Wood",
      foamType: "N/A",
      cushion: "N/A",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: A small, functional table for bedside storage.",
        "Material: Durable wood construction for lasting use.",
        "Durability: Strong frame with excellent finish.",
        "Comfort: Easy access to essentials with additional storage space.",
      ],
    },
    {
      id: 7,
      name: "Study Desk",
      description: "A sleek study desk perfect for your workspace",
      price: 199,
      images: [
        "https://5.imimg.com/data5/SELLER/Default/2022/1/NO/FC/RL/21691826/8719883786780-m-en-hd-1-720x.jpg",
        "https://images-na.ssl-images-amazon.com/images/I/61d7zSY589L.jpg",
        "https://cdn.fynd.com/v2/falling-surf-7c8bb8/fyprod/wrkr/products/pictures/item/free/original/rTvlH2S32-NEUDOT-Cruze-Corner-Study-Table-Leon-Teak-or-Corner-Study-Table-for-Students-or-1-Wood-Study-Table-or-Office-Table-or-Desk-for-Work-from-Home-or-1-Year-Warranty.jpeg",
        "https://m.media-amazon.com/images/I/71MCOOE8HSL._AC_SL1500_.jpg"
      ],
      availableColors: ["Wooden", "Black", "White"],
      designs: ["Modern", "Compact"],
      customizationOption: "Available in various sizes and finishes.",
      dimensions: "40(L) x 24(B) x 30(H)",
      upholsteryMaterial: "Wood",
      foamType: "N/A",
      cushion: "N/A",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Sleek and functional, ideal for study or work.",
        "Material: Strong wood construction for durability.",
        "Durability: Solid frame with sturdy legs.",
        "Comfort: Spacious work area with plenty of storage options.",
      ],
    },
    {
      id: 8,
      name: "Sectional Sofa",
      description: "A modern sectional sofa that provides ample seating for the whole family",
      price: 1499,
      images: [
        "https://indiannest.in/cdn/shop/files/Izayuh_110.63__Wide_Upholstered_Sofa_with_Chaise_longue_2.jpg?v=1692110105&width=1445",
        "https://www.dreamzzfurniture.com/wp-content/uploads/2021/01/Live-Image-1.png",
        "https://craftsmill.in/cdn/shop/files/modular-sectional-sofas-powder-blue-cotton-blend-fabric-derek-modular-u-shaped-sofa-with-ottoman-62-left-chaise-with-34-ottoman-123-middle-62-right-chaise-with-34-ottoman-465666666007_2048x.jpg?v=1725047317",
        "https://cdn.shopify.com/s/files/1/0096/4594/9013/files/Sectional_sofa_set-12.jpg?v=1653917990"
      ],
      availableColors: ["Charcoal", "Light Grey"],
      designs: ["Modern", "Spacious"],
      customizationOption: "Available in different configurations.",
      dimensions: "120(L) x 40(B) x 38(H)",
      upholsteryMaterial: "Leather",
      foamType: "Pocket Springs with High-Density Foam",
      cushion: "Plush",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Luxurious sectional with deep cushions and wide armrests.",
        "Material: Premium leather upholstery for long-lasting comfort.",
        "Durability: Reinforced frame with high-quality foam.",
        "Comfort: Plush cushions that offer ultimate relaxation.",
      ],
    },
    {
      id: 9,
      name: "Single Sofa",
      description: "A comfortable single sofa perfect for individual seating",
      price: 299,
      images: [
        "https://static.vecteezy.com/system/resources/previews/023/635/899/non_2x/modern-sofa-isolated-illustration-ai-generative-free-photo.jpg",
        "https://luxuryofhomes.com/cdn/shop/products/OTTER_SINGLE_SOFA_1.jpg?v=1669367877",
        "https://png.pngtree.com/thumb_back/fw800/background/20220312/pngtree-single-simple-sofa-living-room-home-decoration-design-image_994857.jpg",
        "https://bantia.in/cdn/shop/products/bf-lbox030101-3_1000x.jpg?v=1661329986"
      ],
      availableColors: ["Black", "Beige"],
      designs: ["Modern", "Simple"],
      customizationOption: "Available with different fabric options.",
      dimensions: "35(L) x 35(B) x 30(H)",
      upholsteryMaterial: "Fabric",
      foamType: "High-Density Foam",
      cushion: "Soft",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Compact and sleek, perfect for small spaces.",
        "Material: Durable fabric upholstery with a soft feel.",
        "Durability: Strong wooden frame and high-quality foam.",
        "Comfort: Soft cushions for comfortable seating.",
      ],
    },
    {
      id: 10,
      name: "2-Seater Sofa",
      description: "A cozy two-seater sofa perfect for small living rooms",
      price: 599,
      images: [
        "https://febonic.com/cdn/shop/files/02_79509b6b-dc5c-4162-9f16-8717d8e8e643.jpg?v=1719921555&width=2048",
        "https://www.hometown.in/cdn/shop/files/1_f3b7ad30-9dd6-483a-ae7a-5355d75e48f6.jpg?v=1717146771",
        "https://gravityshade.com/wp-content/uploads/grsfs002-01.webp",
        "https://myseventhheaven.in/cdn/shop/products/2seaterskybluesofamoodshot_540x.jpg?v=1735363233",

      ],
      availableColors: ["Grey", "Beige"],
      designs: ["Modern", "Functional"],
      customizationOption: "Available with different cushion firmness and fabric.",
      dimensions: "55(L) x 30(B) x 35(H)",
      upholsteryMaterial: "Polyester Blend",
      foamType: "High-Density Foam",
      cushion: "Medium Firm",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: A sleek two-seater ideal for small living spaces.",
        "Material: Soft and durable polyester blend upholstery.",
        "Durability: Reinforced wooden frame for long-lasting use.",
        "Comfort: Medium-firm cushions for excellent support.",
      ],
    },
    {
      id: 11,
      name: "3-Seater Sofa",
      description: "A spacious three-seater sofa for ultimate comfort",
      price: 799,
      images: [
        "https://www.getmycouch.com/cdn/shop/files/TordonSideTable_91.png?v=1706446940",
        "https://ouchcart.com/cdn/shop/files/cc13d5a6404a8aaa010c295be4a1b700_600x_508d2a29-431a-4247-98c2-97bfefb11c01.webp?v=1721402987",
        "https://m.media-amazon.com/images/I/715I0CDBrvL._AC_UF894,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/81ZjbJ2CdVL._AC_UF894,1000_QL80_.jpg"
      ],
      availableColors: ["Beige", "Light Grey"],
      designs: ["Contemporary", "Comfort"],
      customizationOption: "Customizable with various cushion and fabric options.",
      dimensions: "80(L) x 36(B) x 38(H)",
      upholsteryMaterial: "Fabric",
      foamType: "High-Density Foam",
      cushion: "Medium Firm",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Stylish three-seater with ample space for relaxation.",
        "Material: Soft and durable fabric upholstery.",
        "Durability: Strong construction for long-lasting use.",
        "Comfort: Medium-firm cushions for maximum comfort.",
      ],
    },
    {
      id: 12,
      name: "Leather Sofa",
      description: "A luxurious leather sofa for your living space",
      price: 1299,
      images: [
        "https://w0.peakpx.com/wallpaper/94/252/HD-wallpaper-purple-stylish-leather-sofa-living-room-modern-interior-design-minimalism-table-on-the-floor.jpg"
,        "https://img.freepik.com/free-photo/brown-sofa-blue-room_1194-6647.jpg?semt=ais_hybrid",
        "https://image.made-in-china.com/202f0j00zZNhWqgIkSkn/Brown-Vintage-Italian-Modern-Faux-Leather-Sofa-with-Metal-Leg-for-Living-Room.jpg",
        "https://s.alicdn.com/@sc04/kf/H3db9f7665c6a429592f7106075a4df4cZ.png_720x720q50.png",
        
      ],
      availableColors: ["Black", "Brown", "Tan"],
      designs: ["Modern", "Classic"],
      customizationOption: "Available with different leather finishes.",
      dimensions: "90(L) x 36(B) x 38(H)",
      upholsteryMaterial: "Genuine Leather",
      foamType: "High-Density Foam",
      cushion: "Firm",
      legsMaterial: "Wood",
      salientFeatures: [
        "Design: Elegant leather sofa with a luxurious feel.",
        "Material: High-quality leather that gets better with time.",
        "Durability: Reinforced wooden frame for excellent stability.",
        "Comfort: Firm cushions for ultimate support and relaxation.",
      ],
    },
  ];


  export default products